const actionTypes = {
  RESET_STATE: "RESET_STATE",
  FETCHING_STARTED: "FETCHING_STARTED",
  FETCHING_COMPLETED: "FETCHING_COMPLETED",
  UPDATE_PAGE_NUMBER: "UPDATE_PAGE_NUMBER",
  UPDATE_PAGE_SIZE: "UPDATE_PAGE_SIZE",
  UPDATE_PAGE_TOTAL: "UPDATE_PAGE_TOTAL",
};

export default actionTypes;
