const actionTypes = {
  RESET_STATE: "RESET_STATE",
  UPDATE_FILTERS: "UPDATE_FILTERS",
  OPEN_UPDATE_FROM: "OPEN_UPDATE_FROM",
  CLOSE_UPDATE_FROM: "CLOSE_UPDATE_FROM",
  OPEN_ROW_MENU: "OPEN_ROW_MENU",
  CLOSE_ROW_MENU: "CLOSE_ROW_MENU",
  ACTIVATE_BIN_MODE: "ACTIVATE_BIN_MODE",
  DEACTIVATE_BIN_MODE: "DEACTIVATE_BIN_MODE",
  UPDATE_ROW_MENU_CURRENT_RECORD: "UPDATE_ROW_MENU_CURRENT_RECORD",
  UPDATE_ROW_MENU_POSITION: "UPDATE_ROW_MENU_POSITION",
};

export default actionTypes;
