const permissionRegexMap = {
    "*": /.*/,
    "organization.*": /.*/,
    // branch
    "branch.*": /^branch\.[a-z]+$/,
    "branch.update": /^branch\.update$/,
    "branch.read": /^branch\.read$/,
    "branch.manage": /^branch\.manage$/,
    "branch.create": /^branch\.create$/,
    // product
    "product.*": /^product\.[a-z]+$/,
    "product.update": /^product\.update$/,
    "product.create": /^product\.create$/,
    "product.manage": /^product\.manage$/,
    // productCategory
    "productCategory.*": /^product-category\.[a-z]+$/,
    "productCategory.update": /^product-category\.update+$/,
    "productCategory.create": /^product-category\.create$/,
    // productSubCategory
    "productSubCategory.*": /^product-sub-category\.[a-z]+$/,
    "productSubCategory.create": /^product-sub-category\.create$/,
    "productSubCategory.update": /^product-sub-category\.update$/,
    // productStock
    "productStock.*": /^product-stock\.[a-z]+$/,
    // product price
    "productPrice.*": /^product-price\.[a-z]+$/,
    "productPrice.update": /^product-price\.update$/,
    "productPrice.create": /^product-price\.create$/,
    "productPrice.manage": /^product-price\.manage$/,
    "productPrice.read": /^product-price\.read$/,
    "productLatestPricesView": /^product-latest-prices-view\.[a-z]+$/,
    // account
    "account.*": /^account(-[a-z]+)?\.[a-z]+$/,
    // accountType
    "accountType.*": /^account-type\.[a-z]+$/,
    // accountSubtype
    "accountSubtype.*": /^account-subtype\.[a-z]+$/,
    // address
    "address.*": /^address\.[a-z]+$/,
    // inventory
    "inventory.*": /^inventory\.[a-z]+$/,
    "inventory.update": /^inventory\.update$/,
    "inventory.manage": /^inventory\.manage$/,
    "inventory.read": /^inventory\.read$/,
    // uom
    "uom.*": /^uom\.[a-z]+$/,
    "uom.update": /^uom\.update$/,
    "uom.create": /^uom\.create$/,
    // uomConverstions
    "uomConversion.*": /^uom-conversion\.[a-z]+$/,
    // tagsMetadata
    "tagMetadata.*": /^tag-metadata\.[a-z]+$/,
    "tagMetadata.update": /^tag-metadata\.update$/,
    "tagMetadata.create": /^tag-metadata\.create$/,
    "tagMetadata.manage": /^tag-metadata\.manage$/,
    // brand
    "brand.*": /^brand\.[a-z]+$/,
    "brand.update": /^brand\.update+$/,
    "brand.create": /^brand\.create+$/,
    // taxIdentity
    "taxIdentity.*": /^tax-identity\.[a-z]+$/,
    // iam
    "iam": /^(user|privilege|role)\.[a-z]+$/,
    // user
    "user.*": /^user\.[a-z]+$/,
    "user.manage": /^user\.manage$/,
    "user.update": /^user\.update$/,
    "user.create": /^user\.create$/,
    // role
    "role.*": /^role\.[a-z]+$/,
    "role.manage": /^role\.manage$/,
    "role.update": /^role\.update$/,
    "role.create": /^role\.create$/,
    // privilege
    "privilege.*": /^privilege\.[a-z]+$/,
    "privilege.manage": /^privilege\.manage$/,
    "privilege.update": /^privilege\.update$/,
    "privilege.create": /^privilege\.create$/,


} satisfies { [key: string]: RegExp };

export default permissionRegexMap;